name: 'Create Leanpub Preview'
description: 'Triggers the build of a new preview and waits until it is ready'
runs:
  using: 'composite'
  inputs:
    apikey:
      description: 'Leanpub API Key'
      required: true
    slug:
      description: 'Leanpub Book Slug'
      required: true
  outputs:
    pdf_url:
      description: 'URL to the PDF'
  steps:
    - run: ./preview.sh
      shell: bash
